name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # hoặc 'master' tùy nhánh bạn đang dùng

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push student_service
        uses: docker/build-push-action@v5
        with:
          context: ./student_service
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/student_service:latest

      - name: Build & Push stats_service
        uses: docker/build-push-action@v5
        with:
          context: ./stats_service
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/stats_service:latest
